# Generated by Django 5.2.15 on 2026-09-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0023_alter_user_rabbitmq_queue_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="affiliation",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="team_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
