# Generated by Django 5.2.17 on 2026-09-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_remove_user_is_bot'),
        ('profiles', '0024_user_affiliation_user_team_name'),
    ]

    operations = [
    ]
